In [4]:
%%timeit
import numpy as np
from numba import jit

a = np.arange(1, 10 ** 7)
b = np.arange(-10 ** 7, -1)

@jit(nopython=True)
def sum_sequence(a, b):
    result = np.zeros_like(a)
    for i in range(len(a)):
        result[i] = a[i] - b[i]
    return result
print(sum_sequence(a,b))

[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001

In [5]:
%%timeit
import numpy as np

a = np.arange(1, 10 ** 7)
b = np.arange(-10 ** 7, -1)

def sum_sequence(a, b):
    result = np.zeros_like(a)
    for i in range(len(a)):
        result[i] = a[i] - b[i]
    return result
print(sum_sequence(a,b))

[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
[10000001 10000001 10000001 ... 10000001 10000001 10000001]
4.39 s ± 29 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
import cupy as cp

a = cp.arange(1, 10 ** 7)
b = cp.arange(-10 ** 7, -1)

def sum_sequence(a, b):
    result = cp.zeros_like(a)
    for i in range(len(a)):
        result[i] = a[i] - b[i]
    return result
print(sum_sequence(a,b))

[10000001 10000001 10000001 ... 10000001 10000001 10000001]
